/* tslint:disable */
/* eslint-disable */
/**
 * lnbits client
 * API for LNbits, the free and open source bitcoin wallet and accounts system with plugins.
 *
 * The version of the OpenAPI document: 0.10.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConversionData
 */
export interface ConversionData {
    /**
     * 
     * @type {string}
     * @memberof ConversionData
     */
    from?: string;
    /**
     * 
     * @type {number}
     * @memberof ConversionData
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof ConversionData
     */
    to?: string;
}

/**
 * Check if a given object implements the ConversionData interface.
 */
export function instanceOfConversionData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "amount" in value;

    return isInstance;
}

export function ConversionDataFromJSON(json: any): ConversionData {
    return ConversionDataFromJSONTyped(json, false);
}

export function ConversionDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversionData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'from': !exists(json, 'from') ? undefined : json['from'],
        'amount': json['amount'],
        'to': !exists(json, 'to') ? undefined : json['to'],
    };
}

export function ConversionDataToJSON(value?: ConversionData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'from': value.from,
        'amount': value.amount,
        'to': value.to,
    };
}

