/* tslint:disable */
/* eslint-disable */
/**
 * lnbits client
 * API for LNbits, the free and open source bitcoin wallet and accounts system with plugins.
 *
 * The version of the OpenAPI document: 0.10.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateExtension
 */
export interface CreateExtension {
    /**
     * 
     * @type {string}
     * @memberof CreateExtension
     */
    extId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateExtension
     */
    archive: string;
    /**
     * 
     * @type {string}
     * @memberof CreateExtension
     */
    sourceRepo: string;
}

/**
 * Check if a given object implements the CreateExtension interface.
 */
export function instanceOfCreateExtension(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "extId" in value;
    isInstance = isInstance && "archive" in value;
    isInstance = isInstance && "sourceRepo" in value;

    return isInstance;
}

export function CreateExtensionFromJSON(json: any): CreateExtension {
    return CreateExtensionFromJSONTyped(json, false);
}

export function CreateExtensionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateExtension {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'extId': json['ext_id'],
        'archive': json['archive'],
        'sourceRepo': json['source_repo'],
    };
}

export function CreateExtensionToJSON(value?: CreateExtension | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ext_id': value.extId,
        'archive': value.archive,
        'source_repo': value.sourceRepo,
    };
}

