/* tslint:disable */
/* eslint-disable */
/**
 * lnbits client
 * API for LNbits, the free and open source bitcoin wallet and accounts system with plugins.
 *
 * The version of the OpenAPI document: 0.10.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateLnurlAuth
 */
export interface CreateLnurlAuth {
    /**
     * 
     * @type {string}
     * @memberof CreateLnurlAuth
     */
    callback: string;
}

/**
 * Check if a given object implements the CreateLnurlAuth interface.
 */
export function instanceOfCreateLnurlAuth(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "callback" in value;

    return isInstance;
}

export function CreateLnurlAuthFromJSON(json: any): CreateLnurlAuth {
    return CreateLnurlAuthFromJSONTyped(json, false);
}

export function CreateLnurlAuthFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLnurlAuth {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'callback': json['callback'],
    };
}

export function CreateLnurlAuthToJSON(value?: CreateLnurlAuth | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'callback': value.callback,
    };
}

