/* tslint:disable */
/* eslint-disable */
/**
 * lnbits client
 * API for LNbits, the free and open source bitcoin wallet and accounts system with plugins.
 *
 * The version of the OpenAPI document: 0.10.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTopup
 */
export interface CreateTopup {
    /**
     * 
     * @type {string}
     * @memberof CreateTopup
     */
    walletId: string;
    /**
     * 
     * @type {number}
     * @memberof CreateTopup
     */
    amount: number;
}

/**
 * Check if a given object implements the CreateTopup interface.
 */
export function instanceOfCreateTopup(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "walletId" in value;
    isInstance = isInstance && "amount" in value;

    return isInstance;
}

export function CreateTopupFromJSON(json: any): CreateTopup {
    return CreateTopupFromJSONTyped(json, false);
}

export function CreateTopupFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTopup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'walletId': json['wallet_id'],
        'amount': json['amount'],
    };
}

export function CreateTopupToJSON(value?: CreateTopup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'wallet_id': value.walletId,
        'amount': value.amount,
    };
}

