/* tslint:disable */
/* eslint-disable */
/**
 * lnbits client
 * API for LNbits, the free and open source bitcoin wallet and accounts system with plugins.
 *
 * The version of the OpenAPI document: 0.10.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateInvoiceData
 */
export interface CreateInvoiceData {
    /**
     * 
     * @type {boolean}
     * @memberof CreateInvoiceData
     */
    out?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CreateInvoiceData
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateInvoiceData
     */
    memo?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateInvoiceData
     */
    unit?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateInvoiceData
     */
    descriptionHash?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateInvoiceData
     */
    unhashedDescription?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateInvoiceData
     */
    expiry?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateInvoiceData
     */
    lnurlCallback?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateInvoiceData
     */
    lnurlBalanceCheck?: string;
    /**
     * 
     * @type {object}
     * @memberof CreateInvoiceData
     */
    extra?: object;
    /**
     * 
     * @type {string}
     * @memberof CreateInvoiceData
     */
    webhook?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateInvoiceData
     */
    internal?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateInvoiceData
     */
    bolt11?: string;
}

/**
 * Check if a given object implements the CreateInvoiceData interface.
 */
export function instanceOfCreateInvoiceData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateInvoiceDataFromJSON(json: any): CreateInvoiceData {
    return CreateInvoiceDataFromJSONTyped(json, false);
}

export function CreateInvoiceDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInvoiceData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'out': !exists(json, 'out') ? undefined : json['out'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'memo': !exists(json, 'memo') ? undefined : json['memo'],
        'unit': !exists(json, 'unit') ? undefined : json['unit'],
        'descriptionHash': !exists(json, 'description_hash') ? undefined : json['description_hash'],
        'unhashedDescription': !exists(json, 'unhashed_description') ? undefined : json['unhashed_description'],
        'expiry': !exists(json, 'expiry') ? undefined : json['expiry'],
        'lnurlCallback': !exists(json, 'lnurl_callback') ? undefined : json['lnurl_callback'],
        'lnurlBalanceCheck': !exists(json, 'lnurl_balance_check') ? undefined : json['lnurl_balance_check'],
        'extra': !exists(json, 'extra') ? undefined : json['extra'],
        'webhook': !exists(json, 'webhook') ? undefined : json['webhook'],
        'internal': !exists(json, 'internal') ? undefined : json['internal'],
        'bolt11': !exists(json, 'bolt11') ? undefined : json['bolt11'],
    };
}

export function CreateInvoiceDataToJSON(value?: CreateInvoiceData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'out': value.out,
        'amount': value.amount,
        'memo': value.memo,
        'unit': value.unit,
        'description_hash': value.descriptionHash,
        'unhashed_description': value.unhashedDescription,
        'expiry': value.expiry,
        'lnurl_callback': value.lnurlCallback,
        'lnurl_balance_check': value.lnurlBalanceCheck,
        'extra': value.extra,
        'webhook': value.webhook,
        'internal': value.internal,
        'bolt11': value.bolt11,
    };
}

