/* tslint:disable */
/* eslint-disable */
/**
 * lnbits client
 * API for LNbits, the free and open source bitcoin wallet and accounts system with plugins.
 *
 * The version of the OpenAPI document: 0.10.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DecodePayment
 */
export interface DecodePayment {
    /**
     * 
     * @type {string}
     * @memberof DecodePayment
     */
    data: string;
}

/**
 * Check if a given object implements the DecodePayment interface.
 */
export function instanceOfDecodePayment(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function DecodePaymentFromJSON(json: any): DecodePayment {
    return DecodePaymentFromJSONTyped(json, false);
}

export function DecodePaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): DecodePayment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': json['data'],
    };
}

export function DecodePaymentToJSON(value?: DecodePayment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data,
    };
}

