/* tslint:disable */
/* eslint-disable */
/**
 * lnbits client
 * API for LNbits, the free and open source bitcoin wallet and accounts system with plugins.
 *
 * The version of the OpenAPI document: 0.10.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Base class for settings, allowing values to be overridden by environment variables.
 * 
 * This is useful in production for secrets you do not wish to save in code, it plays nicely with docker(-compose),
 * Heroku and any 12 factor app design.
 * @export
 * @interface EditableSettings
 */
export interface EditableSettings {
    /**
     * 
     * @type {number}
     * @memberof EditableSettings
     */
    lightningInvoiceExpiry?: number;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    boltzNetwork?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    boltzUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    boltzMempoolSpaceUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    boltzMempoolSpaceUrlWs?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lntipsApiEndpoint?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lntipsApiKey?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lntipsAdminKey?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lntipsInvoiceKey?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    sparkUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    sparkToken?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    opennodeApiEndpoint?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    opennodeKey?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    opennodeAdminKey?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    opennodeInvoiceKey?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lnpayApiEndpoint?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lnpayApiKey?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lnpayWalletKey?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lnpayAdminKey?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lndGrpcEndpoint?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lndGrpcCert?: string;
    /**
     * 
     * @type {number}
     * @memberof EditableSettings
     */
    lndGrpcPort?: number;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lndGrpcAdminMacaroon?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lndGrpcInvoiceMacaroon?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lndGrpcMacaroon?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lndGrpcMacaroonEncrypted?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lndRestEndpoint?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lndRestCert?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lndRestMacaroon?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lndRestMacaroonEncrypted?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lndCert?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lndAdminMacaroon?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lndInvoiceMacaroon?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lndRestAdminMacaroon?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lndRestInvoiceMacaroon?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    eclairUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    eclairPass?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    corelightningRpc?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    clightningRpc?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    clicheEndpoint?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lnbitsEndpoint?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lnbitsKey?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lnbitsAdminKey?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lnbitsInvoiceKey?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    fakeWalletSecret?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lnbitsBackendWalletClass?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lnbitsRateLimitNo?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lnbitsRateLimitUnit?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EditableSettings
     */
    lnbitsAllowedIps?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof EditableSettings
     */
    lnbitsBlockedIps?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof EditableSettings
     */
    lnbitsNotifications?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EditableSettings
     */
    lnbitsKillswitch?: boolean;
    /**
     * 
     * @type {number}
     * @memberof EditableSettings
     */
    lnbitsKillswitchInterval?: number;
    /**
     * 
     * @type {boolean}
     * @memberof EditableSettings
     */
    lnbitsWatchdog?: boolean;
    /**
     * 
     * @type {number}
     * @memberof EditableSettings
     */
    lnbitsWatchdogInterval?: number;
    /**
     * 
     * @type {number}
     * @memberof EditableSettings
     */
    lnbitsWatchdogDelta?: number;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lnbitsStatusManifest?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lnbitsBaseurl?: string;
    /**
     * 
     * @type {number}
     * @memberof EditableSettings
     */
    lnbitsReserveFeeMin?: number;
    /**
     * 
     * @type {number}
     * @memberof EditableSettings
     */
    lnbitsReserveFeePercent?: number;
    /**
     * 
     * @type {number}
     * @memberof EditableSettings
     */
    lnbitsServiceFee?: number;
    /**
     * 
     * @type {boolean}
     * @memberof EditableSettings
     */
    lnbitsHideApi?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lnbitsDenomination?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lnbitsSiteTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lnbitsSiteTagline?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lnbitsSiteDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lnbitsDefaultWalletName?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EditableSettings
     */
    lnbitsThemeOptions?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lnbitsCustomLogo?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lnbitsAdSpaceTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof EditableSettings
     */
    lnbitsAdSpace?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EditableSettings
     */
    lnbitsAdSpaceEnabled?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof EditableSettings
     */
    lnbitsAllowedCurrencies?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof EditableSettings
     */
    lnbitsAdminExtensions?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof EditableSettings
     */
    lnbitsExtensionsManifests?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof EditableSettings
     */
    lnbitsAdminUsers?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof EditableSettings
     */
    lnbitsAllowedUsers?: Array<string>;
}

/**
 * Check if a given object implements the EditableSettings interface.
 */
export function instanceOfEditableSettings(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EditableSettingsFromJSON(json: any): EditableSettings {
    return EditableSettingsFromJSONTyped(json, false);
}

export function EditableSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditableSettings {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lightningInvoiceExpiry': !exists(json, 'lightning_invoice_expiry') ? undefined : json['lightning_invoice_expiry'],
        'boltzNetwork': !exists(json, 'boltz_network') ? undefined : json['boltz_network'],
        'boltzUrl': !exists(json, 'boltz_url') ? undefined : json['boltz_url'],
        'boltzMempoolSpaceUrl': !exists(json, 'boltz_mempool_space_url') ? undefined : json['boltz_mempool_space_url'],
        'boltzMempoolSpaceUrlWs': !exists(json, 'boltz_mempool_space_url_ws') ? undefined : json['boltz_mempool_space_url_ws'],
        'lntipsApiEndpoint': !exists(json, 'lntips_api_endpoint') ? undefined : json['lntips_api_endpoint'],
        'lntipsApiKey': !exists(json, 'lntips_api_key') ? undefined : json['lntips_api_key'],
        'lntipsAdminKey': !exists(json, 'lntips_admin_key') ? undefined : json['lntips_admin_key'],
        'lntipsInvoiceKey': !exists(json, 'lntips_invoice_key') ? undefined : json['lntips_invoice_key'],
        'sparkUrl': !exists(json, 'spark_url') ? undefined : json['spark_url'],
        'sparkToken': !exists(json, 'spark_token') ? undefined : json['spark_token'],
        'opennodeApiEndpoint': !exists(json, 'opennode_api_endpoint') ? undefined : json['opennode_api_endpoint'],
        'opennodeKey': !exists(json, 'opennode_key') ? undefined : json['opennode_key'],
        'opennodeAdminKey': !exists(json, 'opennode_admin_key') ? undefined : json['opennode_admin_key'],
        'opennodeInvoiceKey': !exists(json, 'opennode_invoice_key') ? undefined : json['opennode_invoice_key'],
        'lnpayApiEndpoint': !exists(json, 'lnpay_api_endpoint') ? undefined : json['lnpay_api_endpoint'],
        'lnpayApiKey': !exists(json, 'lnpay_api_key') ? undefined : json['lnpay_api_key'],
        'lnpayWalletKey': !exists(json, 'lnpay_wallet_key') ? undefined : json['lnpay_wallet_key'],
        'lnpayAdminKey': !exists(json, 'lnpay_admin_key') ? undefined : json['lnpay_admin_key'],
        'lndGrpcEndpoint': !exists(json, 'lnd_grpc_endpoint') ? undefined : json['lnd_grpc_endpoint'],
        'lndGrpcCert': !exists(json, 'lnd_grpc_cert') ? undefined : json['lnd_grpc_cert'],
        'lndGrpcPort': !exists(json, 'lnd_grpc_port') ? undefined : json['lnd_grpc_port'],
        'lndGrpcAdminMacaroon': !exists(json, 'lnd_grpc_admin_macaroon') ? undefined : json['lnd_grpc_admin_macaroon'],
        'lndGrpcInvoiceMacaroon': !exists(json, 'lnd_grpc_invoice_macaroon') ? undefined : json['lnd_grpc_invoice_macaroon'],
        'lndGrpcMacaroon': !exists(json, 'lnd_grpc_macaroon') ? undefined : json['lnd_grpc_macaroon'],
        'lndGrpcMacaroonEncrypted': !exists(json, 'lnd_grpc_macaroon_encrypted') ? undefined : json['lnd_grpc_macaroon_encrypted'],
        'lndRestEndpoint': !exists(json, 'lnd_rest_endpoint') ? undefined : json['lnd_rest_endpoint'],
        'lndRestCert': !exists(json, 'lnd_rest_cert') ? undefined : json['lnd_rest_cert'],
        'lndRestMacaroon': !exists(json, 'lnd_rest_macaroon') ? undefined : json['lnd_rest_macaroon'],
        'lndRestMacaroonEncrypted': !exists(json, 'lnd_rest_macaroon_encrypted') ? undefined : json['lnd_rest_macaroon_encrypted'],
        'lndCert': !exists(json, 'lnd_cert') ? undefined : json['lnd_cert'],
        'lndAdminMacaroon': !exists(json, 'lnd_admin_macaroon') ? undefined : json['lnd_admin_macaroon'],
        'lndInvoiceMacaroon': !exists(json, 'lnd_invoice_macaroon') ? undefined : json['lnd_invoice_macaroon'],
        'lndRestAdminMacaroon': !exists(json, 'lnd_rest_admin_macaroon') ? undefined : json['lnd_rest_admin_macaroon'],
        'lndRestInvoiceMacaroon': !exists(json, 'lnd_rest_invoice_macaroon') ? undefined : json['lnd_rest_invoice_macaroon'],
        'eclairUrl': !exists(json, 'eclair_url') ? undefined : json['eclair_url'],
        'eclairPass': !exists(json, 'eclair_pass') ? undefined : json['eclair_pass'],
        'corelightningRpc': !exists(json, 'corelightning_rpc') ? undefined : json['corelightning_rpc'],
        'clightningRpc': !exists(json, 'clightning_rpc') ? undefined : json['clightning_rpc'],
        'clicheEndpoint': !exists(json, 'cliche_endpoint') ? undefined : json['cliche_endpoint'],
        'lnbitsEndpoint': !exists(json, 'lnbits_endpoint') ? undefined : json['lnbits_endpoint'],
        'lnbitsKey': !exists(json, 'lnbits_key') ? undefined : json['lnbits_key'],
        'lnbitsAdminKey': !exists(json, 'lnbits_admin_key') ? undefined : json['lnbits_admin_key'],
        'lnbitsInvoiceKey': !exists(json, 'lnbits_invoice_key') ? undefined : json['lnbits_invoice_key'],
        'fakeWalletSecret': !exists(json, 'fake_wallet_secret') ? undefined : json['fake_wallet_secret'],
        'lnbitsBackendWalletClass': !exists(json, 'lnbits_backend_wallet_class') ? undefined : json['lnbits_backend_wallet_class'],
        'lnbitsRateLimitNo': !exists(json, 'lnbits_rate_limit_no') ? undefined : json['lnbits_rate_limit_no'],
        'lnbitsRateLimitUnit': !exists(json, 'lnbits_rate_limit_unit') ? undefined : json['lnbits_rate_limit_unit'],
        'lnbitsAllowedIps': !exists(json, 'lnbits_allowed_ips') ? undefined : json['lnbits_allowed_ips'],
        'lnbitsBlockedIps': !exists(json, 'lnbits_blocked_ips') ? undefined : json['lnbits_blocked_ips'],
        'lnbitsNotifications': !exists(json, 'lnbits_notifications') ? undefined : json['lnbits_notifications'],
        'lnbitsKillswitch': !exists(json, 'lnbits_killswitch') ? undefined : json['lnbits_killswitch'],
        'lnbitsKillswitchInterval': !exists(json, 'lnbits_killswitch_interval') ? undefined : json['lnbits_killswitch_interval'],
        'lnbitsWatchdog': !exists(json, 'lnbits_watchdog') ? undefined : json['lnbits_watchdog'],
        'lnbitsWatchdogInterval': !exists(json, 'lnbits_watchdog_interval') ? undefined : json['lnbits_watchdog_interval'],
        'lnbitsWatchdogDelta': !exists(json, 'lnbits_watchdog_delta') ? undefined : json['lnbits_watchdog_delta'],
        'lnbitsStatusManifest': !exists(json, 'lnbits_status_manifest') ? undefined : json['lnbits_status_manifest'],
        'lnbitsBaseurl': !exists(json, 'lnbits_baseurl') ? undefined : json['lnbits_baseurl'],
        'lnbitsReserveFeeMin': !exists(json, 'lnbits_reserve_fee_min') ? undefined : json['lnbits_reserve_fee_min'],
        'lnbitsReserveFeePercent': !exists(json, 'lnbits_reserve_fee_percent') ? undefined : json['lnbits_reserve_fee_percent'],
        'lnbitsServiceFee': !exists(json, 'lnbits_service_fee') ? undefined : json['lnbits_service_fee'],
        'lnbitsHideApi': !exists(json, 'lnbits_hide_api') ? undefined : json['lnbits_hide_api'],
        'lnbitsDenomination': !exists(json, 'lnbits_denomination') ? undefined : json['lnbits_denomination'],
        'lnbitsSiteTitle': !exists(json, 'lnbits_site_title') ? undefined : json['lnbits_site_title'],
        'lnbitsSiteTagline': !exists(json, 'lnbits_site_tagline') ? undefined : json['lnbits_site_tagline'],
        'lnbitsSiteDescription': !exists(json, 'lnbits_site_description') ? undefined : json['lnbits_site_description'],
        'lnbitsDefaultWalletName': !exists(json, 'lnbits_default_wallet_name') ? undefined : json['lnbits_default_wallet_name'],
        'lnbitsThemeOptions': !exists(json, 'lnbits_theme_options') ? undefined : json['lnbits_theme_options'],
        'lnbitsCustomLogo': !exists(json, 'lnbits_custom_logo') ? undefined : json['lnbits_custom_logo'],
        'lnbitsAdSpaceTitle': !exists(json, 'lnbits_ad_space_title') ? undefined : json['lnbits_ad_space_title'],
        'lnbitsAdSpace': !exists(json, 'lnbits_ad_space') ? undefined : json['lnbits_ad_space'],
        'lnbitsAdSpaceEnabled': !exists(json, 'lnbits_ad_space_enabled') ? undefined : json['lnbits_ad_space_enabled'],
        'lnbitsAllowedCurrencies': !exists(json, 'lnbits_allowed_currencies') ? undefined : json['lnbits_allowed_currencies'],
        'lnbitsAdminExtensions': !exists(json, 'lnbits_admin_extensions') ? undefined : json['lnbits_admin_extensions'],
        'lnbitsExtensionsManifests': !exists(json, 'lnbits_extensions_manifests') ? undefined : json['lnbits_extensions_manifests'],
        'lnbitsAdminUsers': !exists(json, 'lnbits_admin_users') ? undefined : json['lnbits_admin_users'],
        'lnbitsAllowedUsers': !exists(json, 'lnbits_allowed_users') ? undefined : json['lnbits_allowed_users'],
    };
}

export function EditableSettingsToJSON(value?: EditableSettings | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lightning_invoice_expiry': value.lightningInvoiceExpiry,
        'boltz_network': value.boltzNetwork,
        'boltz_url': value.boltzUrl,
        'boltz_mempool_space_url': value.boltzMempoolSpaceUrl,
        'boltz_mempool_space_url_ws': value.boltzMempoolSpaceUrlWs,
        'lntips_api_endpoint': value.lntipsApiEndpoint,
        'lntips_api_key': value.lntipsApiKey,
        'lntips_admin_key': value.lntipsAdminKey,
        'lntips_invoice_key': value.lntipsInvoiceKey,
        'spark_url': value.sparkUrl,
        'spark_token': value.sparkToken,
        'opennode_api_endpoint': value.opennodeApiEndpoint,
        'opennode_key': value.opennodeKey,
        'opennode_admin_key': value.opennodeAdminKey,
        'opennode_invoice_key': value.opennodeInvoiceKey,
        'lnpay_api_endpoint': value.lnpayApiEndpoint,
        'lnpay_api_key': value.lnpayApiKey,
        'lnpay_wallet_key': value.lnpayWalletKey,
        'lnpay_admin_key': value.lnpayAdminKey,
        'lnd_grpc_endpoint': value.lndGrpcEndpoint,
        'lnd_grpc_cert': value.lndGrpcCert,
        'lnd_grpc_port': value.lndGrpcPort,
        'lnd_grpc_admin_macaroon': value.lndGrpcAdminMacaroon,
        'lnd_grpc_invoice_macaroon': value.lndGrpcInvoiceMacaroon,
        'lnd_grpc_macaroon': value.lndGrpcMacaroon,
        'lnd_grpc_macaroon_encrypted': value.lndGrpcMacaroonEncrypted,
        'lnd_rest_endpoint': value.lndRestEndpoint,
        'lnd_rest_cert': value.lndRestCert,
        'lnd_rest_macaroon': value.lndRestMacaroon,
        'lnd_rest_macaroon_encrypted': value.lndRestMacaroonEncrypted,
        'lnd_cert': value.lndCert,
        'lnd_admin_macaroon': value.lndAdminMacaroon,
        'lnd_invoice_macaroon': value.lndInvoiceMacaroon,
        'lnd_rest_admin_macaroon': value.lndRestAdminMacaroon,
        'lnd_rest_invoice_macaroon': value.lndRestInvoiceMacaroon,
        'eclair_url': value.eclairUrl,
        'eclair_pass': value.eclairPass,
        'corelightning_rpc': value.corelightningRpc,
        'clightning_rpc': value.clightningRpc,
        'cliche_endpoint': value.clicheEndpoint,
        'lnbits_endpoint': value.lnbitsEndpoint,
        'lnbits_key': value.lnbitsKey,
        'lnbits_admin_key': value.lnbitsAdminKey,
        'lnbits_invoice_key': value.lnbitsInvoiceKey,
        'fake_wallet_secret': value.fakeWalletSecret,
        'lnbits_backend_wallet_class': value.lnbitsBackendWalletClass,
        'lnbits_rate_limit_no': value.lnbitsRateLimitNo,
        'lnbits_rate_limit_unit': value.lnbitsRateLimitUnit,
        'lnbits_allowed_ips': value.lnbitsAllowedIps,
        'lnbits_blocked_ips': value.lnbitsBlockedIps,
        'lnbits_notifications': value.lnbitsNotifications,
        'lnbits_killswitch': value.lnbitsKillswitch,
        'lnbits_killswitch_interval': value.lnbitsKillswitchInterval,
        'lnbits_watchdog': value.lnbitsWatchdog,
        'lnbits_watchdog_interval': value.lnbitsWatchdogInterval,
        'lnbits_watchdog_delta': value.lnbitsWatchdogDelta,
        'lnbits_status_manifest': value.lnbitsStatusManifest,
        'lnbits_baseurl': value.lnbitsBaseurl,
        'lnbits_reserve_fee_min': value.lnbitsReserveFeeMin,
        'lnbits_reserve_fee_percent': value.lnbitsReserveFeePercent,
        'lnbits_service_fee': value.lnbitsServiceFee,
        'lnbits_hide_api': value.lnbitsHideApi,
        'lnbits_denomination': value.lnbitsDenomination,
        'lnbits_site_title': value.lnbitsSiteTitle,
        'lnbits_site_tagline': value.lnbitsSiteTagline,
        'lnbits_site_description': value.lnbitsSiteDescription,
        'lnbits_default_wallet_name': value.lnbitsDefaultWalletName,
        'lnbits_theme_options': value.lnbitsThemeOptions,
        'lnbits_custom_logo': value.lnbitsCustomLogo,
        'lnbits_ad_space_title': value.lnbitsAdSpaceTitle,
        'lnbits_ad_space': value.lnbitsAdSpace,
        'lnbits_ad_space_enabled': value.lnbitsAdSpaceEnabled,
        'lnbits_allowed_currencies': value.lnbitsAllowedCurrencies,
        'lnbits_admin_extensions': value.lnbitsAdminExtensions,
        'lnbits_extensions_manifests': value.lnbitsExtensionsManifests,
        'lnbits_admin_users': value.lnbitsAdminUsers,
        'lnbits_allowed_users': value.lnbitsAllowedUsers,
    };
}

